#!/bin/bash

# set environments (dir path...)
SCRIPT_PATH="$(readlink -f "$0")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
SCRIPT_NAME="$(basename "$SCRIPT_PATH")"

ROOT_DIR="$(readlink -f "$SCRIPT_DIR"/..)"
BUILD_DIR="$ROOT_DIR/build"

BITS="64"
ISA="rv${BITS}gc"
ABI="lp64d"
#CROSS_COMPILE= $YOUR_LOCATION

PLATFORM="generic"

SBI_SRC_DIR="$ROOT_DIR/sbi"

OUTPUT_DIR="$ROOT_DIR/output"
SBI_OUT="$OUTPUT_DIR/sm"
BOOTROM_OUT="$OUTPUT_DIR/bootrom"


echo $SM_SRC_DIR
rm -rf opensbi/build
#make -C opensbi O=build PLATFORM_DIR="$SM_SRC_DIR"/plat/$PLATFORM FW_PIC=n CROSS_COMPILE=riscv$BITS-unknown-elf- \
#    FW_PAYLOAD=y LATFORM_RISCV_XLEN=$BITS PLATFORM_RISCV_ISA=$ISA PLATFORM_RISCV_ABI=$ABI
make -C opensbi O=build PLATFORM_DIR="$SBI_SRC_DIR"/plat/$PLATFORM FW_PIC=n \
    FW_PAYLOAD=y LATFORM_RISCV_XLEN=$BITS PLATFORM_RISCV_ISA=$ISA PLATFORM_RISCV_ABI=$ABI\
    CROSS_COMPILE=$CROSS_COMPILE
